version: "3.9"
services:
    flask:
        build: .
        env_file:
            - ./.env
        command: python app.py
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        